variables:
  project: oss-download
  SolutionDirectory: src/
  BuildConfiguration: Release

name: OSSGadget_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r) $(project)
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - src/oss-download
    - src/Shared
pr:
  branches:
    include:
    - master
  paths:
    include:
    - Pipelines/oss-download.yml
    - src/oss-download
    - src/Shared

steps:
- template: oss-core.yml
  parameters:
    project: $(project)