# Azure Pipelines
# https://aka.ms/yaml

variables:
  project: oss-characteristics

name: OSSGadget_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r) $(project)
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - src/$(project)
    - src/Shared
pr:
  branches:
    include:
    - master
  paths:
    include:
    - Pipelines
    - src/$(project)
    - src/Shared

stages:
- stage: Test
  jobs:
  - job: build_test
    displayName: Run OSS Gadget Tests
    pool:
      vmImage: 'windows-latest'
    steps:
    - template: oss-tests.yml

- stage: Build
  jobs:
  - job: build_nix
    displayName: Linux & Mac
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: build-oss-component-mac-linux.yml
      parameters: 
        project: $(project)


  - job: build_win
    displayName: Windows, NetCoreApp, Nupkg
    pool:
      vmImage: 'windows-latest'
    steps:
    - template: build-oss-component-windows-nuget.yml
      parameters: 
        project: $(project)

  - job: sign_hash_release
    displayName: Code Sign, Generate Hashes, Publish Public Releases
    dependsOn:
    - build_nix
    - build_win
    condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Manual'))
    pool:
      vmImage: 'windows-latest'
    steps:
    - template: sign-and-publish-oss-component.yml
      parameters:
        project:  $(project)